import Provider from "./Provider";
import Link from "next/link";
import { Button } from "./common/components/index";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#ffffff",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head />
      <body>
        <Provider>
          <header>
            <h1>
              <Link href="/">ブログ</Link>
            </h1>
            <Button>ボタン</Button>
          </header>
          {children}
          <footer>
            <small>© 2023 azukiazusa</small>
          </footer>
        </Provider>
      </body>
    </html>
  );
}
