import Provider from "./Provider";
import Link from "next/link";
//layoutComponents
import Header from "./layoutcomponents/Header";
import Footer from "./layoutcomponents/Footer";
import Main from "./layoutcomponents/Main";
//:::::::::::::::::::::::::::::::::::::::::::::
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#ffffff",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head />
      <body>
        <Provider>
          <Header />
          <Main>{children}</Main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
